django_web_service/about/urls.py
# deep_app의 urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.outline, name='outline'),
]

django_web_service/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # main/
    path('signup_signin/', views.signup_signin, name='signup_signin'),
    path('signout/', views.signout, name='signout'),
]

django_web_service/final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')), # 메인 시작화면 주소
    path('outline/', include('about.urls')),
    path('deep_app/', include('deep_app.urls')),
    path('accounts/', include('accounts.urls')),
    # path('input_image/result', include('deep_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_web_service/main_app/urls.py
# urls.py
# 이 두줄은 외우자
from django.urls import path
from . import views

app_name = 'main_app'

urlpatterns = [
    # main/
    path('', views.index, name='index'),
    path('login/', views.login, name='login')
]
######

django_web_service/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Yummy Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  <!-- Favicons -->
  <script src="{% static '/js/jquery-3.7.1.min.js' %}"></script>
  <script src="{% static '/js/food_map.js' %}"></script>
  <link href="{% static '/main/assets/img/favicon.png' %}" rel="icon">
  <link href="{% static '/main/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static '/main/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static '/main/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static '/main/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static '/main/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static '/main/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{%static '/main/assets/css/main.css' %}" rel="stylesheet">
  {% block additional_css %}
  
  {% endblock additional_css %}
  
  <!-- Map Script -->
  <script type="text/javascript" src="https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=my70djses9"></script>

  

  <!-- =======================================================
  * Template Name: Yummy
  * Updated: Jan 09 2024 with Bootstrap v5.3.2
  * Template URL: https://bootstrapmade.com/yummy-bootstrap-restaurant-website-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="{% block body_class %}{% endblock body_class %}">
  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="{% url 'main_app:index' %}" class="logo d-flex align-items-center me-auto me-lg-0">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1>KFR<span>.</span></h1>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'main_app:index' %}">Home</a></li>
          <li><a href="{% url 'about:outline' %}">About</a></li>
          <li><a href="/deep_app/input_image">Analyze</a></li>
          <li><a href="{% url 'food_map_form' %}">Recommend</a></li>
        </ul>
      </nav><!-- .navbar -->
    
      {% comment %} 로그인/회원가입/로그아웃  {% endcomment %}
      {% if not request.user.is_authenticated %}
      <a class="btn-book-a-table" href="{% url "accounts:signup_signin" %}">Sign In / Sign Up</a>

      {% else %}
      <a class="btn-book-a-table" href="{% url "accounts:signout" %}">Sign Out</a>
      
      {% endif %}

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
    </div>
  </header><!-- End Header -->

  {% block content %}
  
  {% endblock content %}
  
      <!-- ======= Footer ======= -->
<footer id="footer" class="footer">

  <div class="container">
    <div class="row gy-3">
      <div class="col-lg-3 col-md-6 d-flex">
        <div>
          <h4>developer</h4>
          <p>
            Kim Sungwoo <br>
            Kim Myeongjun <br>
            Seo Juewon <br>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="copyright">
      &copy; Copyright <strong><span>Yummy</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/yummy-bootstrap-restaurant-website-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </div>

  </footer><!-- End Footer -->
  <!-- End Footer -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'main/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'main/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'main/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'main/assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'main/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'main/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'main/assets/js/main.js' %}"></script>

</body>

</html>